version: "3"
services:
  backend:
    image: node:lts
    ports:
      - "4000:4000"
    working_dir: /app
    networks:
      - app-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
      - ../mercury-sdk:/mercury-sdk
    depends_on:
      - pgdb
    stdin_open: true
    tty: true

  pgdb:
    image: postgres:14
    restart: always
    container_name: pgdb
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

volumes: 
  db-volume:
