services:
  backend:
    build: .
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - ../mercury-sdk:/mercury-sdk
    depends_on:
      - pgdb

  pgdb:
    image: postgres:14
    restart: always
    container_name: pgdb
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env
  
networks: 
  app-network:
    driver: bridge

volumes: 
  db-volume:
